### ISSUE TITLE
Sync/Compatibility Issues

### ISSUE THREAD

**Issue by LoafOrc** [LoafOrc/FacilityMeltdown#13]
If you are experiencing sync issues with meltdown please share your ENTIRE mod list as a comment to this issue. Make sure to include all versions as well as your game version and other details like who the meltdown started for.

**Comment by rileyb123** [comment]
The meltdown only started for the host. Apparatus also would spawn right outside the ship and could not be seen by the host.

Game Version: v49

Mods:
BepInEx-BepInExPack-5.4.2100
notnotnotswipez-MoreCompany-1.7.6
RugbugRedfern-Skinwalkers-4.0.1
tinyhoot-ShipLoot-1.0.0
Ozone-Runtime_Netcode_Patcher-0.2.5
Sligili-More_Emotes-1.3.3
x753-More_Suits-1.4.1
anormaltwig-LateCompany-1.0.11
RickArg-Helmet_Cameras-2.1.5
FlipMods-ReservedItemSlotCore-1.8.17
FlipMods-ReservedFlashlightSlot-1.6.3
Suskitech-AlwaysHearActiveWalkies-1.4.4
sunnobunno-YippeeMod-1.2.3
FlipMods-ReservedWalkieSlot-1.6.2
Rune580-LethalCompany_InputUtils-0.6.3
Renegades-FlashlightToggle-1.5.0
EliteMasterEric-Coroner-1.6.0
Renegades-WalkieUse-1.5.0
Jordo-NeedyCats-1.1.1
vasanex-ItemQuickSwitch-1.1.0
TwinDimensionalProductions-CoilHeadStare-1.0.5
Drakorle-MoreItems-1.0.2
matsuura-HealthMetrics-1.0.2
sfDesat-ExpansionAssets-1.1.0
HolographicWings-LethalExpansion-1.3.25
sfDesat-Orion-1.3.0
FlipMods-BetterStamina-1.3.2
Evaisa-HookGenPatcher-0.0.5
Owen3H-CSync-1.0.6
Evaisa-LethalLib-0.14.2
NotAtomicBomb-TerminalApi-1.5.1
loaforc-FacilityMeltdown-2.2.2
KoderTeh-Boombox_Controller-1.2.0
IAmBatby-LethalLevelLoader-1.0.7
Badham_Mods-SCPFoundationDungeon-2.3.1
Midge-PushCompany-1.2.0
MegaPiggy-BuyableShotgun-1.0.4
Thorlar-HealthStation-1.0.1
FlipMods-MoreBlood-1.0.2
Electric131-OuijaBoard-1.5.2
sfDesat-Aquatis-1.1.1
taffyko-NameplateTweaks-1.0.6
xCeezy-LethalEscape-0.8.5
jaspercreations-Scopophobia-1.1.1
TheFluff-FairAI-1.3.2
Zingar-Atlas_Abyss-1.1.6
Azim-LethalPresents-1.0.4
Kittenji-Dont_Touch_Me-1.2.1
Caseuhdeeyuh-MolesterLootBug-1.1.0
kelp-Adidas_Suit-1.0.1
JujuSuits-JujutsuSuits-1.1.3
OE_Tweaks-Possessed_Masks-2.0.4
no00ob-LCSoundTool-1.5.1
Clementinise-CustomSounds-2.3.2
Astanpaeus-CreepyGirl-1.0.0
gerpy-Gerpys_Ambience_and_Escape_Music-1.1.3
BatTeam-LethalFashion-1.0.6
jockie-LethalExpansionCore-1.3.15
TryToDiveMe-Bikini_Bottom-2.1.0
MetalPipeSFX-HornMoan-2.1.0

**Comment by JFlowersB** [comment]
The meltdown only started for the host. Apparatus also would spawn right outside the ship and could not be seen by the host.
Apparatus humming will always be heard by host on ship once Apparatus has been put there, sound also stacks.
Game Version: v49

modpack: 018d768f-4a51-10cd-abb9-f5e7b89fb1e9
Mods:

BepInEx-BepInExPack-5.4.2100
2018-LC_API-3.4.5
notnotnotswipez-MoreCompany-1.7.6
anormaltwig-LateCompany-1.0.11
bizzlemip-BiggerLobby-2.6.0
RugbugRedfern-Skinwalkers-4.0.1
x753-Mimics-2.3.2
x753-More_Suits-1.4.1
RickArg-Helmet_Cameras-2.1.5
FlipMods-ReservedItemSlotCore-1.8.17
FlipMods-ReservedFlashlightSlot-1.6.3
FlipMods-ReservedWalkieSlot-1.6.2
AlexCodesGames-AdditionalSuits-2.0.0
sunnobunno-YippeeMod-1.2.3
PopleZoo-BetterItemScan-3.0.1
amnsoft-EmployeeAssignments-1.1.0
FutureSavior-Boombox_Sync_Fix-1.1.2
PortableNavi-BetterInverseTeleporter-1.0.2
rhydiaan-NicerTeleporters-1.1.1
Sligili-More_Emotes-1.3.3
Jordo-NeedyCats-1.1.1
Ozone-Runtime_Netcode_Patcher-0.2.5
AlexCodesGames-AdditionalContentFramework-1.0.3
jockie-LethalExpansionCore-1.3.15
IAmBatby-LethalLevelLoader-1.0.7
KayNetsua-E_Gypt_Moon-2.0.13
FireNoobsta-Ducks_Moons-1.1.3
sfDesat-Orion-1.3.0
Evaisa-LethalLib-0.14.2
HolographicWings-LethalExpansion-1.3.25
Zingar-Atlas_Abyss-1.1.6
Zingar-SecretLabs-3.3.4
TeamBridget-Peaches_Castle-1.0.41
sfDesat-Aquatis-1.1.1
Ceelery-Kast-1.0.3
Evaisa-HookGenPatcher-0.0.5
FlipMods-BetterStamina-1.3.2
Electric131-OuijaBoard-1.5.2
FlipMods-TooManyEmotes-1.8.6
AinaVT-LethalConfig-1.3.4
Rune580-LethalCompany_InputUtils-0.6.3
Gemumoddo-LethalEmotesAPI-1.4.0
Gemumoddo-BadAssCompany-1.1.4
sfDesat-Celest-0.2.1
sfDesat-ExpansionAssets-1.1.0
MegaPiggy-BuyableShotgun-1.0.4
MegaPiggy-BuyableShotgunShells-1.0.5
JunLethalCompany-GamblingMachineAtTheCompany-1.3.5
no00ob-LCSoundTool-1.5.1
Suskitech-AlwaysHearActiveWalkies-1.4.4
malco-SellBodies-1.1.0
Sligili-HDLethalCompany-1.5.6
Rozebud-FOV_Adjust-1.1.1
Evaisa-LethalThings-0.9.4
taffyko-BetterSprayPaint-2.0.2
NotAtomicBomb-TerminalApi-1.5.1
Dammsugare-KeepScrap-1.0.0
HolographicWings-LEDefaultModules-1.3.25
Blorb-WeatherMultipliers-1.1.0
akechii-DiscountAlert-2.3.0
Drakorle-MoreItems-1.0.2
Renegades-WalkieUse-1.5.0
malco-Lategame_Upgrades-3.1.1
CyanBlob-Motion_Tracker-1.0.0
MassiveNewCoilers-FixCentipedeLag-2023.12.7
vasanex-ItemQuickSwitch-1.1.0
EliteMasterEric-Coroner-1.6.0
NutNutty-SellTracker-1.2.1
KoderTeh-Boombox_Controller-1.2.0
NotAtomicBomb-Terminal_Clock-1.0.5
FlipMods-ReservedSprayPaintSlot-1.0.7
Magic_Wesley-Infernis-1.5.2
Magic_Wesley-Etern-1.3.4
GarrettFTW-Abandoned_Manor-1.3.1
AmazingPyroAndGoofs-Aridion-1.2.6
Hotoni-TZPReworkedHealing-1.3.0
Onyx_Inoculum-Longer_Day-1.0.0
Tolian-Celestria-0.2.1
loaforc-FacilityMeltdown-2.2.2
Ryokune-Physics_Items-0.1.22
Clementinise-CustomSounds-2.3.2
LethalResonance-LETHALRESONANCE-3.0.6
Lordfirespeed-OdinSerializer-2022.11.9
xilophor-LethalNetworkAPI-2.1.4
Piggy-LC_Office-1.0.3

**Comment by Camawama** [comment]
The same issue is happening on my modpack. It appears to only happen on VOW. It also appears that the SHIP DOOR gets stuck opened after taking off. The logs also say this before the aparatus is taken:
![aparatus ](https://github.com/LoafOrc/FacilityMeltdown/assets/43620900/5f07ecb5-dc27-46f4-ab5d-75e688ec318e)


and the logs say this after it is taken:
![after taken](https://github.com/LoafOrc/FacilityMeltdown/assets/43620900/553da91b-b774-4d0f-88ad-7ac41271444e)

**Comment by Camawama** [comment]
Also found out that the problem only occurs on the facility map and any other custom/modded interior is perfectly fine.

**Comment by DevourerOfSuns** [comment]
I tried on two modpacks (One with other mods and one without anything other than the meltdown and its dependencies) and got the same issues. The meltdown only started for the host. Apparatus also would spawn right outside the ship and could not be seen by the host, most notably on Vow and one of the custom maps. As well, the apparatus would appear invisible in the ship for everyone but the host once pulled, or not show up in the apparatus room for everyone but host on both packs.

Game Version: v49
Modfull modpack: 018d76b4-05af-1069-d27b-fb002ddda0fb
Mods: 
BepInEx-BepInExPack-5.4.2100
notnotnotswipez-MoreCompany-1.7.6
Sligili-More_Emotes-1.3.3
anormaltwig-LateCompany-1.0.11
x753-More_Suits-1.4.1
TeamClark-SCP_Foundation_Suit-1.1.0
ManiaBania-1000_Quota_Stare-1.0.0
AlexCodesGames-AdditionalSuits-2.0.0
AlexCodesGames-AdditionalContentFramework-1.0.3
Hexnet111-SuitSaver-1.1.4
Drakorle-MoreItems-1.0.2
Spyci-CozyImprovements-1.2.2
Pooble-LCBetterSaves-1.7.3
FlipMods-FasterItemDropship-1.2.1
tinyhoot-ShipLoot-1.0.0
RickArg-Helmet_Cameras-2.1.5
EliteMasterEric-Coroner-1.6.0
Mugen-FreeJesterPlus-1.0.0
RugbugRedfern-Skinwalkers-4.0.1
FlipMods-MoreBlood-1.0.2
sfDesat-Celest-0.2.1
sfDesat-Aquatis-1.1.1
sfDesat-Orion-1.3.0
KayNetsua-E_Gypt_Moon-2.0.13
Ceelery-Kast-1.0.3
Zingar-SecretLabs-3.3.4
FireNoobsta-Ducks_Moons-1.1.3
Zingar-Atlas_Abyss-1.1.6
AudioKnight-StarlancerMoons-0.5.1
Badham_Mods-SCPFoundationDungeon-2.3.1
scoopy-Scoopys_Variety_Mod-1.1.0
Piggy-LC_Office-1.0.3
xilophor-LethalNetworkAPI-2.1.4
Lordfirespeed-OdinSerializer-2022.11.9
Backrooms-Backrooms-0.1.3
Vulf-GokuBracken-1.5.1
x753-Mimics-2.3.2
jaspercreations-Scopophobia-1.1.1
HomelessGinger-MaskedEnemyOverhaul-3.1.2
NomnomAB-RollingGiant-2.5.1
loaforc-FacilityMeltdown-2.2.2
Owen3H-CSync-1.0.6
BudgetAirpods-InsanityRemastered-1.1.2
NotAtomicBomb-TerminalApi-1.5.1
HolographicWings-LethalExpansion-1.3.25
jockie-LethalExpansionCore-1.3.15
sfDesat-ExpansionAssets-1.1.0
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.14.2
IAmBatby-LethalLevelLoader-1.0.7
Ozone-Runtime_Netcode_Patcher-0.2.5
no00ob-LCSoundTool-1.5.1
Clementinise-CustomSounds-2.3.2
AinaVT-LethalConfig-1.3.4

Game Version: v49
Vanilla modpack:  018d76af-f00b-20c9-d7e7-538bf8729abf
Mods:
BepInExPack v5.4.2100
Evaisa-HookGenPatcher-0.0.5
Owen3H-CSync-1.0.6
Evaisa-LethalLib-0.14.2
NotAtomicBomb-TerminalApi-1.5.1
loaforc-FacilityMeltdown-2.2.2

**Comment by Camawama** [comment]
After removing CSync, the issue no longer happens!!!!

**Comment by KKaydoom** [comment]
Thats weird considering the facilility meltdown made me download that in the first place i am also having these problems

**Comment by Vizorkid** [comment]
> After removing CSync, the issue no longer happens!!!!

Are you sure? We (me and my friend) tried this, and it just completely disabled the mod.

**Comment by JFlowersB** [comment]
Removing Csync disables the mod. I think we just have to wait.

**Comment by Welowas** [comment]
For anyone encountering these issues, this only started happening for me with v2.2.1 and v.2.2.2 (probably also v2.2.0 but I didn't play it on that version) with CSync added. When I rolled the FacilityMeltdown mod back to v2.1.1 and uninstalled CSync everything was working fine again so maybe this could help you too for now.

The issues I was facing were the same as above with the apparatus next to the ship and not in the facility for people who aren't the host while it is normal for the host (nothing outside the ship). On v2.2.1 picking up the one outside the ship would just do nothing and you would be stuck holding it without being able to drop it. On v2.2.2 it would start the meltdown but you would still not be able to drop it.

Here is my list of mods:
BepInExPack v5.4.2100 by BepInEx
Skinwalkers v4.0.1 by RugbugRedfern
ReservedItemSlotCore v1.8.17 by FlipMods
ReservedWalkieSlot v1.6.2 by FlipMods
UnreliableWeatherReports v1.0.0 by MatthiewPurple
MeteoMultiplier v1.1.3 by Fredolx
ItemQuickSwitch v1.1.0 by vasanex
CrossHair v1.1.0 by CTNOriginals
ShipLoot v1.0.0 by tinyhoot
Hold_Scan_Button v1.1.1 by FutureSavior
LethalCompany_InputUtils v0.6.3 by Rune580
SpectateEnemies v2.3.0 by AllToasters
LateCompany v1.0.11 by anormaltwig
Helmet_Cameras v2.1.5 by RickArg
LethalExpansion v1.3.25 by HolographicWings
Quagmire_Scrap v1.0.2 by a_za
CoilHeadStare v1.0.5 by TwinDimensionalProductions
RollingGiant v2.5.1 by NomnomAB
ExpansionAssets v1.1.0 by sfDesat
Aquatis v1.1.1 by sfDesat
Kast v1.0.3 by Ceelery
HookGenPatcher v0.0.5 by Evaisa
LethalLib v0.14.2 by Evaisa
TerminalApi v1.5.1 by NotAtomicBomb
FacilityMeltdown v2.2.2 by loaforc
TermSpeak v1.1.0 by KodiCraft
FairAI v1.3.2 by TheFluff
CSync v1.0.6 by Owen3H

Or just a code to import all these:
018d7738-638d-01d5-970e-9d304d9d676d

**Comment by LoafOrc** [comment]
holy fuck,
alright thanks everybody for the mod lists
it won't be csync (at least not itself) as I verified last night that meltdown worked by itself and it's dependencies
also thank you @Camawama for that error message, looks like something is preventing clients from properly adding the radiation source OR incorrectly setting the override value

**Comment by LoafOrc** [comment]
I'll be having a hotfix go out sometime when I get home to ensure that all players have the meltdown start or borne l none of them do

**Comment by BryantWilliams5** [comment]
Glad to hear that!  Just because I do not see anyone above who tested just the mod, I downloaded only Facility Meltdown (and its dependencies) and still had the same issue.  Apparatus outside, no meltdown effects or sounds for clients.  I saw the same error Camawama did when loading a level.  I additionally saw this sync error when joining the host's lobby.  In this case it is showing me the host's file structure and giving an access authority error trying to sync the configs.
![image](https://github.com/LoafOrc/FacilityMeltdown/assets/42980902/b20f99d8-8817-4b7a-9277-b99b7248dc65)
![image](https://github.com/LoafOrc/FacilityMeltdown/assets/42980902/48212e4a-de36-4126-891c-0afbe38ab82e)

**Comment by BryantWilliams5** [comment]
Forgot the mod versions list.
![image](https://github.com/LoafOrc/FacilityMeltdown/assets/42980902/0c1750bf-b2f6-4709-baf4-88974df93a83)

**Comment by LoafOrc** [comment]
seems like csync does have some issues sometimes, can not wait for this to be an env specific issue

**Comment by Paradox75831004** [comment]
LETHAL_LONERS: 018d777f-2fce-19e6-5f10-39c3e81ede95

**Comment by LoafOrc** [comment]
![Screenshot_20240205-153830](https://github.com/LoafOrc/FacilityMeltdown/assets/33192068/89980fe1-8614-4fdc-af25-07362428e14e)

including recent conversation from discord
seems like csync hasn't been tested at scale like this so it isn't able to handle it well

**Comment by Camawama** [comment]
> Removing Csync disables the mod. I think we just have to wait.

Welp, I guess we didn't fully test that :\

**Comment by LoafOrc** [comment]
hot fix version 2.2.3 is going live now which disables config syncing. i wanted to get it out immediately so there could be other issues but make sure all players have the same config as of now

**Comment by LoafOrc** [comment]
2.2.4 is going live i built the wrong branch 💀

**Comment by LoafOrc** [comment]
alright unable to reproduce on v2.2.2 in online mod with mods that were shared by everybody, going to need log files from everybody

**Comment by LoafOrc** [comment]
fixed in v1.0.7 of csync thank you everybody for providing a modlist while this issue was worked out!
https://github.com/Owen3H/CSync/commit/6097a574bbf67d633d87189dd944f6e3d3e7e854
