### ISSUE TITLE
Implementing a Random Event Trigger with a 5% Probability

### ISSUE THREAD

**Issue by Katsugami** [LoafOrc/FacilityMeltdown#24]
Hello,

I would like to know if it's possible to assign a probability percentage that triggers the scenario when the fuse is removed.

In other words, I'm looking to use this event randomly, having the possibility that it doesn't trigger every time, but with a 5% chance that this event occurs. This way, it would truly become an unexpected moment.

Thank you, sincerely.

**Comment by LoafOrc** [comment]
https://youtu.be/pdqy3J5LF5M?si=wN_rLQeBWajOGBQS
