### ISSUE TITLE
[Issue] update to csync 2.0.0

### ISSUE THREAD

**Issue by CoolLKKPS** [LoafOrc/FacilityMeltdown#25]
**I HAVE COMPLETED THE FOLLOWING**
 - [ ] I have already joined the [lethal company modding discord](https://discord.gg/lcmod) and gone to the [FacilityMeltdown thread](https://discord.com/channels/1168655651455639582/1191847266777042985) and checked the issue is not already present
 > Discord does not available in my region
 - [x] I have checked the issue page for both open and closed issues that could be relevant.
 - [ ] I have attached my latest log file while having debug logs enabled.
 > don't even need that
 - [x] I have reproduced the issue.
 - [ ] I will fill out the information below to the best of my ability.
 > not necessary

## Describe the bug
update to csync 2.0.0

## To Reproduce
u don't have to reproduce

## Expected behaviour
n/a

## Environment
n/a

## Modlist
n/a

### Additonal Context
idk how to quote the code but, hope im doing right

https://github.com/LoafOrc/FacilityMeltdown/blob/05e490e40e5200e44ccf04972a0a95c8f4ee632d/Util/MeltdownConfig.cs#L27
> change to: 
>     internal class MeltdownConfig : SyncedConfig\<MeltdownConfig\> {

https://github.com/LoafOrc/FacilityMeltdown/blob/05e490e40e5200e44ccf04972a0a95c8f4ee632d/Util/MeltdownConfig.cs#L46-L47
> change to: 
>         internal MeltdownConfig(ConfigFile file) : base("FacilityMeltdown") {
>             ConfigManager.Register(this);

u can check the csync [wiki](https://thunderstore.io/c/lethal-company/p/Owen3H/CSync/wiki/1681-updating-to-v200) to check what need to changed

**Comment by LoafOrc** [comment]
yes i know, im dealing with personal stuff and this will be fixed sometime today. the creator of csync personally reached out to me to inform me. for now revert to csync v1.0.8 until meltdown 2.4 is released

**Comment by LoafOrc** [comment]
fixed in meltdown v2.4.0
