### ISSUE TITLE
Error encountered when starting the game without creating a room

### ISSUE THREAD

**Issue by apeng0907** [LoafOrc/FacilityMeltdown#26]
[Info   :   BepInEx] Loading [FacilityMeltdown 2.4.0]
[Info   :me.loaforc.facilitymeltdown] Initalising assets...
[Info   :me.loaforc.facilitymeltdown] Doing networky stuff
[Error  : Unity Log] ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load file or assembly 'me.loaforc.soundapi, Version=0.1.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'me.loaforc.soundapi, Version=0.1.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'me.loaforc.soundapi, Version=0.1.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
System.Reflection.Assembly.GetTypes () (at <787acc3c9a4c471ba7d971300105af24>:IL_0000)
FacilityMeltdown.MeltdownPlugin.RegisterNetworking () (at D:/LethalCompanyModding/FacilityMeltdown/MeltdownPlugin.cs:101)
FacilityMeltdown.MeltdownPlugin.Awake () (at D:/LethalCompanyModding/FacilityMeltdown/MeltdownPlugin.cs:45)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

**Comment by LoafOrc** [comment]
fixed in meltdown 2.4.1
