### ISSUE TITLE
LethalSettings issue

### ISSUE THREAD

**Issue by jakeb072001** [LoafOrc/FacilityMeltdown#3]
After the 2.0 update, the mod no longer worked for me.
After taking the core there would be none of the effects of this mod and no matter how long I wait the facility does not explode.

So I finally got around to removing my mods in batches until this mod worked again and found that LethalSettings was breaking this mod after 2.0.

I can play the game fine without LethalSettings so I have removed it from my pack but I thought I would just let you know.

**Comment by LoafOrc** [comment]
lethal settings is not required, considering this issue is 2 days old i have very little faith that you'll provide a log file. if you do though i'll be happy to provide more help

**Comment by jakeb072001** [comment]
Sorry I think I posted this late at night and didn't think of posting a log.
I just retested again and now everything is working fine even with LethalSettings...
I didn't change anything else so I don't really know why its working fine now but I guess this issue can be closed.
