### ISSUE TITLE
Switch back to the original CSync

### ISSUE THREAD

**Issue by ZigzagAwaka** [LoafOrc/FacilityMeltdown#33]
Not an issue but just a qol adjustment for this mod as the CSync fork used has a lot of problems, including beta updates or other stuff.
If you could switch back to https://thunderstore.io/c/lethal-company/p/Owen3H/CSync/ it would be nice
(the original CSync came back a little while ago)

If you don't want to switch back, I completly understand as this mod already works fine, but it would be better imo

**Comment by ZigzagAwaka** [comment]
Last CSync update is completly broken, enable to join other players....
Please switch back to the original CSync

**Comment by LoafOrc** [comment]
no i will not be switching back to owen's
with meltdown 2.5 i updated to lorddfirespeed's csync 4.0.0, this required several changes that i don't want to undo
instead you should look into what mods are using the old versions of csync and either see if they have a version avaliable for the newer csync, not use them, or ask them to update

**Comment by ZigzagAwaka** [comment]
Either something is wrong or i didn't understand but what is lorddfirespeed's csync? (there is only Sigurd and Owen)
Also I think you didn't got the point, right now the last version of Sigurd Csync is not playable... i know the stable release of FacilityMeltdown does not use it but it automatically updates anyway

**Comment by LoafOrc** [comment]
lordfirespeed is sigurd. lordfirespeed is their discord username so ;3
if your having a problem with specifically csync the github is [here](https://github.com/lc-sigurd/CSync)
also what do you mean automatically updates? r2modman/thunderstore always gives you the option to install old versions and just ignore the update message.

**Comment by ZigzagAwaka** [comment]
Oh ok thanks!
Its true, just that i don't want to deal with old updates, and then tell other players to not update the profile etc
Anyway, as you can see the github for Csync has some issues explaining why it's broken, i just created this issue on your github to advise you to switch to the original csync since there is no issue with it
But i completly understood your point, sorry for the bother and have a great day!

**Comment by ZigzagAwaka** [comment]
Thank you for having removed Csync in the last update !
