### ISSUE TITLE
[V50/Error] Triggered meltdown but won't happen any when timed out

### ISSUE THREAD

**Issue by CoolLKKPS** [LoafOrc/FacilityMeltdown#34]
**I HAVE COMPLETED THE FOLLOWING**
 - [ ] I have already joined the [lethal company modding discord](https://discord.gg/lcmod) and gone to the [FacilityMeltdown thread](https://discord.com/channels/1168655651455639582/1191847266777042985) and checked the issue is not already present
 - [ ] I have checked the issue page for both open and closed issues that could be relevant.
 - [ ] I have attached my latest log file while having debug logs enabled.
 - [x] I have reproduced the issue.
 - [ ] I will fill out the information below to the best of my ability.

## Describe the bug
[08:29:11.7923291] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
FacilityMeltdown.MeltdownSequence.MeltdownEffects.SetupEmergencyLights () (at ./MeltdownSequence/MeltdownEffects.cs:16)
FacilityMeltdown.MeltdownSequence.Behaviours.MeltdownHandler.StartMeltdownClientRpc () (at ./MeltdownSequence/Behaviours/MeltdownHandler.cs:80)
FacilityMeltdown.MeltdownSequence.Behaviours.MeltdownHandler.__rpc_handler_3631067672 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <0090a6d312964b2690ec9a8a3ea2e9ad>:0)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:0)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Logger:LogException(Exception, Object)
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass4_0:<LogException>b__0()
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass28_0:<wrapCallback>b__0()
AsyncLoggers.Wrappers.JobWrapper:LogWorker()
AsyncLoggers.Wrappers.LogJob:Execute()
Unity.Jobs.JobStruct`1:Execute(LogJob&, IntPtr, IntPtr, JobRanges&, Int32)

[08:29:11.7938393] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
FacilityMeltdown.MeltdownSequence.MeltdownEffects.SetupEmergencyLights () (at ./MeltdownSequence/MeltdownEffects.cs:16)
FacilityMeltdown.MeltdownSequence.Behaviours.MeltdownHandler.StartMeltdownClientRpc () (at ./MeltdownSequence/Behaviours/MeltdownHandler.cs:80)
FacilityMeltdown.MeltdownSequence.Behaviours.MeltdownHandler.MeltdownReadyServerRpc (System.UInt64 clientId) (at ./MeltdownSequence/Behaviours/MeltdownHandler.cs:166)
FacilityMeltdown.MeltdownSequence.Behaviours.MeltdownHandler.__rpc_handler_2863729516 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <0090a6d312964b2690ec9a8a3ea2e9ad>:0)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:0)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Logger:LogException(Exception, Object)
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass4_0:<LogException>b__0()
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass28_0:<wrapCallback>b__0()
AsyncLoggers.Wrappers.JobWrapper:LogWorker()
AsyncLoggers.Wrappers.LogJob:Execute()
Unity.Jobs.JobStruct`1:Execute(LogJob&, IntPtr, IntPtr, JobRanges&, Int32)

[08:32:27.1721678] [Error  :me.loaforc.facilitymeltdown] MeltdownHandler was disabled without starting a meltdown, a client most likely failed the MeltdownReadyCheck. If you are going to report this make sure to provide ALL client logs.

btw another error log may from ur API mods

[08:29:12.9801739] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
PlayAudioAnimationEvent.PlayAudio3Oneshot () (at <1ff0abda334d405f8f8b4762bb39ae86>:0)

[08:29:12.9801739] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
PlayAudioAnimationEvent.PlayAudio3Oneshot () (at <1ff0abda334d405f8f8b4762bb39ae86>:0)

[08:29:12.9811729] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
PlayAudioAnimationEvent.PlayAudio3Oneshot () (at <1ff0abda334d405f8f8b4762bb39ae86>:0)

[08:29:12.9811729] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
PlayAudioAnimationEvent.PlayAudio3Oneshot () (at <1ff0abda334d405f8f8b4762bb39ae86>:0)

[08:29:13.5661664] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
PlayAudioAnimationEvent.PlayAudio1Oneshot () (at <1ff0abda334d405f8f8b4762bb39ae86>:0)

[08:29:13.5661664] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
PlayAudioAnimationEvent.PlayAudio1Oneshot () (at <1ff0abda334d405f8f8b4762bb39ae86>:0)

[08:29:13.5661664] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
PlayAudioAnimationEvent.PlayAudio1Oneshot () (at <1ff0abda334d405f8f8b4762bb39ae86>:0)

[08:29:13.5661664] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
PlayAudioAnimationEvent.PlayAudio1Oneshot () (at <1ff0abda334d405f8f8b4762bb39ae86>:0)

## Environment
 - OS: Windows 11
 - Lethal Company Version: v50

## Modlist
 - FacilityMeltdown version: 2.5.6

**Comment by CoolLKKPS** [comment]
@LoafOrc FacilityMeltdownExperimental

**Comment by CoolLKKPS** [comment]
also already set MusicVolume = 0, but still have music playing

**Comment by LoafOrc** [comment]
this is a known issue, its been reported in the discord thread and i personally have already had it happen. next time please actually follow the steps.

**Comment by CoolLKKPS** [comment]
i can't use discord in my region, available region are not include for some country, my timezone is UTC+8

**Comment by CoolLKKPS** [comment]
i can't use discord in my region, available region are not include for some country, my timezone is UTC+8
