### ISSUE TITLE
[V50/Error] Geiger Counter not working and softlocking the game

### ISSUE THREAD

**Issue by Damecube** [LoafOrc/FacilityMeltdown#39]
**I HAVE COMPLETED THE FOLLOWING**
 - [ ] I have already joined the [lethal company modding discord](https://discord.gg/lcmod) and gone to the [FacilityMeltdown thread](https://discord.com/channels/1168655651455639582/1191847266777042985) and checked the issue is not already present
 - [x ] I have checked the issue page for both open and closed issues that could be relevant.
 - [x ] I have attached my latest log file while having debug logs enabled.
 - [x ] I have reproduced the issue.
 - [ x] I will fill out the information below to the best of my ability.

## Describe the bug
The Geiger Counter cant be picked up and softlocks the game.

Logs: 
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object.
Stack trace:
GrabbableObject.FallWithCurve () (at <09f109276c764f589f47f312aab5547a>:IL_00A0)
GrabbableObject.Update () (at <09f109276c764f589f47f312aab5547a>:IL_0125)
FacilityMeltdown.Equipment.GeigerCounterItem.Update () (at ./Equipment/GeigerCounterItem.cs:59)

## To Reproduce
Buy the Geiger Counter and open the Loot Ship. The Geiger Counter will fly and cant be picked up. Leaving the planet softlocks the game.

## Environment
 - OS: Windows 10
 - Lethal Company Version: v50

## Modlist
 - FacilityMeltdown version: 2.5.1
 - LethalLib version: 0.15.1
 - HookGenPatcher: 0.0.5
 - FixPluginTypesSerialization: 1.1.1
 - CSync: 4.1.0
 - LobbyCompatibility: 1.1.0
 - BepInExPAck: 5.4.2100
 - MoreMoneyStart: 2.1.0 (Used to recreate it after it happened)

**Comment by LoafOrc** [comment]
yeah i'll probably fix this at some point. fixing the geiger counter isn't too high of a priority for me

**Comment by dopadream** [comment]
> yeah i'll probably fix this at some point. fixing the geiger counter isn't too high of a priority for me

If you're not going to fix it can you at least remove it from the shop for now? I bought it unknowingly and it fucked my save file. No point in keeping it if it does nothing

**Comment by LoafOrc** [comment]
be silly :3

**Comment by RedSun42** [comment]
Could you set a Bool in Config to disable / enable the Geiger Counter ? Thanks :)

**Comment by QRQ-2817** [comment]
Really, could you prioritize this issue? It's breaking peoples games.

**Comment by LoafOrc** [comment]
my bad my life is a little bit more complicated than it was when i started making this mod i guess. this is such a small part of the mod that i genuinely thought no one even used it. i will get to it when i get to it

**Comment by LoafOrc** [comment]
fixed in meltdown v2.6.3

**Comment by QRQ-2817** [comment]
> fixed in meltdown v2.6.3

Thank you
