### ISSUE TITLE
Major issues

### ISSUE THREAD

**Issue by KKaydoom** [LoafOrc/FacilityMeltdown#4]
I swear 3/4 of the times we try to pick up apparatus its either not their for some peoples screens or picking it up locks your interact and drop and we keep having problems of super delayed music being triggered (we tested the mod without the music mod and it still had these problems)
and we keep constantly getting these errors over and over again 
![image](https://github.com/LoafOrc/FacilityMeltdown/assets/106564078/d0606c82-c02d-46cd-8c8c-1f7e2be1917a)

**Comment by KKaydoom** [comment]
And for some reason one of us will just die as soon as the round starts https://cdn.discordapp.com/attachments/789570662397640756/1202494815581900850/2024-01-31_22-04-38.mp4?ex=65cda991&is=65bb3491&hm=973a7de541052edaf999e0fa75d97ded2e628be47b61f92139e4a64e62a55180&

**Comment by LoafOrc** [comment]
a) that error is unrelated
b) are you using a modded interior

**Comment by KKaydoom** [comment]
yeah this only happens on the bunker from more interiors so its probably bc of the map

**Comment by KKaydoom** [comment]
Nvm we still got this issue on default interiors we are currently trying to get logs or video of this (we uninstalled the more interriors mod too)

**Comment by KKaydoom** [comment]
Here is some footage my friend took of the solo cam mod of another guy holding the apparatus and trying to interact with a door
https://github.com/LoafOrc/FacilityMeltdown/assets/106564078/2ce0e089-83e1-4b6f-87ed-19f2a4cae91b
