### ISSUE TITLE
Suggestion: Config Expansion

### ISSUE THREAD

**Issue by Gamersxp6248** [LoafOrc/FacilityMeltdown#47]
Option to enable it only on specific moons, and a list of moons to enable it on.
Option to disable the portal announcement voices that play throughout the entire event (Very immersion breaking)
Option to disable the random explosions that occur throughout the entire event (also very immersion breaking)
Option to disable the status messages.

**Comment by LoafOrc** [comment]
> Option to enable it only on specific moons, and a list of moons to enable it on.
maybe, idk though
could be a good idea to suggest to the meltdown chance people (i dont know if they're taking suggestions though so)

> Option to disable the portal announcement voices that play throughout the entire event (Very immersion breaking)
no

> Option to disable the random explosions that occur throughout the entire event (also very immersion breaking)
Meltdown is made to be chaotic, the random explosions help that and honestly it feels really silent without them

> Option to disable the status messages.
Like the ship dialogue? no?

**Comment by LoafOrc** [comment]
closing with inactivity :3

**Comment by Gamersxp6248** [comment]
That's fine, I found an alternative to this mod that does the same exact thing but with the portal announcements disabled.

I don't get why you don't understand that people want to use your mod and that you have to ruin it by refusing some basic stuff, like the ability to change how the meltdown feels. I personally used your meltdown mod on the Secret Lab map, and another mod to change the music to be the sirens and such from secret lab's alpha warhead, however, one thing that never could be disabled was the portal announcement voices that didn't fit in, and the random explosions that didn't align with the fact it was just a warhead detonation sequence.

In the end, I found an alternative, and if you do or don't want to fix your mod, that doesn't matter to me anymore.
