### ISSUE TITLE
[Bug] Apparatus value doesn't scale with weather multipliers via WeatherRegistry

### ISSUE THREAD

**Issue by ajsglist** [LoafOrc/FacilityMeltdown#50]
**I HAVE COMPLETED THE FOLLOWING**
 - [x] I have already joined the [lethal company modding discord](https://discord.gg/lcmod) and gone to the [FacilityMeltdown thread](https://discord.com/channels/1168655651455639582/1191847266777042985) and checked the issue is not already present
 - [x] I have checked the issue page for both open and closed issues that could be relevant.
 - [n/a] I have attached my latest log file while having debug logs enabled.
 - [x] I have reproduced the issue.
 - [x] I will fill out the information below to the best of my ability.

## Describe the bug
Apparatus value doesn't scale with weather multipliers via WeatherRegistry

## To Reproduce
Steps to reproduce the behaviour:

Set Apparatus value in Meltdown config; set scrap multiplier to value that isn't 1 for desired weather via WeatherRegistry

## Expected behaviour
Apparatus value set in Meltdown config can be adjusted by weather multipliers

## Environment
 - OS: Windows [windows version here]
 - Lethal Company Version: v56

## Modlist
 - FacilityMeltdown 2.6.13
 - WeatherTweaks 0.5.11

### Additonal Context
I can't be sure which mod is better suited to handling a fix for the issue, so I have also posted this report in the WeatherTweaks github and will try to link the two tickets.

Thanks for your time. FacilityMeltdown is an amazing mod!

edit, reference: https://github.com/AndreyMrovol/LethalWeatherRegistry/issues/6

**Comment by LoafOrc** [comment]
oops forgot to close this. this works now
