### ISSUE TITLE
Random Facility Meltdown

### ISSUE THREAD

**Issue by IxRxH** [LoafOrc/FacilityMeltdown#51]
Is it possible to add an option to make the Facility Meltdown event random?

Probably it could be more interesting if the event is not happening every time you get the apparatus.
let me explain, people could think that is complicate to take it if is very far, but if the event have a chance to not happend probably are going to take that risk.

Also, probably having a random timer (example: 1.5 minutes ~ 2.5 minutes) add more risk and fun.

**Comment by LoafOrc** [comment]
No.
Use Meltdown Chance, it's a mod for meltdown that includes the random event but not the random timer.
