### ISSUE TITLE
Is not a bug, but question

### ISSUE THREAD

**Issue by Xeraccoon** [LoafOrc/FacilityMeltdown#53]
I don't know if there was a better place to post this, and if so I apologize.

I was wondering, if you just didn't think to put a countdown on your mod, or if it's intentional, or due to a technical limitation, being able to choose to see the countdown would be very very cool, do you think you could put that? thanks in advance

**Comment by LoafOrc** [comment]
a timer is accessible through the "reactor health" command on the terminal, i dont know where i would put it on the player's hud without it looking weird
